modLoader="javafml"

loaderVersion="[35,)"

license="All rights reserved"

issueTrackerURL="http://my.issue.tracker/"

[[mods]]

modId="aetherium"

version="${file.jarVersion}"


# Display stuff. Purely for UI.
displayName="Aetherium"
logoFile="logio.png"
credits="Microsoft for hosting GitHub, SilentChaos512 for the tutorials, and the kind people using the Stack Overflow services"
authors="GamingZacharyC"
displayURL="https://gamingzacharyc.github.io/Aetherium/"
description='''
This is currently blank for storytelling and winging-it reasons
'''

[[dependencies.aetherium]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aetherium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
