modLoader="javafml"

loaderVersion="[35,)"

license="All rights reserved"

issueTrackerURL="http://my.issue.tracker/"

[[mods]]

modId="aetherium"

version='${Version}'

updateJSONURL="https://raw.githubusercontent.com/GamingZacharyC/Aetherium/update.json/update.json"

# Display stuff. Purely for UI.
displayName="Aetherium"
# TODO: Add a banner (logo)
logoFile="logio.png"
credits="Microsoft for hosting GitHub, SilentChaos512 for the tutorials, and the kind people using the Stack Overflow services"
authors="GamingZacharyC"
displayURL="https://gamingzacharyc.github.io/Aetherium/"
# TODO: Add a real description for the mod
description='''
This is currently blank for storytelling and winging-it reasons
'''

[[dependencies.aetherium]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aetherium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.aetherium]]
    modId="jei"
    mandatory=false
    versionRange="[7.6.1.60,)"
    ordering="AFTER"
    side="BOTH"